class SearchQueries {
  static final List<String> educationLevelsUzbekistan = [
    'Bachelor of Science in Information Technology',
    'Bachelor of Science in Computer Science',
    'Bachelor of Information Technology',
    'Bachelor of Computer Science',
    'Bachelor of Science in Software Engineering',
    'Bachelor of Science in Cybersecurity',
    'Bachelor of Science in Data Science',
    'Bachelor of Science in Information Systems',
    'Master of Science in Information Technology',
    'Master of Science in Computer Science',
    'Master of Computer Science',
    'Master of Information Technology',
    'Master of Science in Software Engineering',
    'Master of Science in Cybersecurity',
    'Master of Science in Data Science',
    'Master of Science in Information Systems',
    'Doctor of Philosophy in Information Technology',
    'Doctor of Philosophy in Computer Science',
    'Doctor of Philosophy in Software Engineering',
    'Doctor of Philosophy in Cybersecurity',
    'Doctor of Philosophy in Data Science',
    'Doctor of Philosophy in Information Systems',
    'Associate\'s Degree in Information Technology',
    'Associate\'s Degree in Computer Science',
    'Diploma in Information Technology',
    'Diploma in Computer Science',
    'Diploma in Software Engineering',
    'Diploma in Cybersecurity',
    'Diploma in Data Science',
    'Diploma in Information Systems',
    'Certificate in Information Technology',
    'Certificate in Computer Science',
    'Certificate in Software Engineering',
    'Certificate in Cybersecurity',
    'Certificate in Data Science',
    'Certificate in Information Systems',
    'Certificate in Network Administration',
    'Postgraduate Diploma in Information Technology',
    'Postgraduate Diploma in Computer Science',
    'Postgraduate Diploma in Software Engineering',
    'Postgraduate Diploma in Cybersecurity',
    'Postgraduate Diploma in Data Science',
    'Postgraduate Diploma in Information Systems',
    'Postgraduate Diploma in Network Administration',
    'Graduate Certificate in Information Technology',
    'Graduate Certificate in Computer Science',
    'Graduate Certificate in Software Engineering',
    'Graduate Certificate in Cybersecurity',
    'Graduate Certificate in Data Science',
    'Graduate Certificate in Information Systems',
    'Graduate Certificate in Network Administration',
    'Professional Certificate in Information Technology',
    'Professional Certificate in Computer Science',
    'Professional Certificate in Software Engineering',
    'Professional Certificate in Cybersecurity',
    'Professional Certificate in Data Science',
    'Professional Certificate in Information Systems',
    'Professional Certificate in Network Administration',
    'Technical Diploma in Information Technology',
    'Technical Diploma in Computer Science',
    'Technical Diploma in Software Engineering',
    'Technical Diploma in Cybersecurity',
    'Technical Diploma in Data Science',
    'Technical Diploma in Information Systems',
    'Technical Diploma in Network Administration',
    'Vocational Diploma in Information Technology',
    'Vocational Diploma in Computer Science',
    'Vocational Diploma in Software Engineering',
    'Vocational Diploma in Cybersecurity',
    'Vocational Diploma in Data Science',
    'Vocational Diploma in Information Systems',
    'Vocational Diploma in Network Administration',
    'Advanced Certificate in Information Technology',
    'Advanced Certificate in Computer Science',
    'Advanced Certificate in Software Engineering',
    'Advanced Certificate in Cybersecurity',
    'Advanced Certificate in Data Science',
    'Advanced Certificate in Information Systems',
    'Advanced Certificate in Network Administration',
    'Online Certificate in Information Technology',
    'Online Certificate in Computer Science',
    'Online Certificate in Software Engineering',
    'Online Certificate in Cybersecurity',
    'Online Certificate in Data Science',
    'Online Certificate in Information Systems',
    'Online Certificate in Network Administration',
    'Distance Learning Diploma in Information Technology',
    'Distance Learning Diploma in Computer Science',
    'Distance Learning Diploma in Software Engineering',
    'Distance Learning Diploma in Cybersecurity',
    'Distance Learning Diploma in Data Science',
    'Distance Learning Diploma in Information Systems',
    'Distance Learning Diploma in Network Administration'
  ];
}
